### ISSUE TITLE
Failing 2 CI tests on Windows - Py3.7 and Py3.8

### ISSUE THREAD

**Issue by sumerc** [sumerc/yappi#31]
```bash
======================================================================
FAIL: test_async_wall (test_asyncio_context_vars.AsyncUsage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\test_asyncio_context_vars.py", line 50, in test_async_wall
    self.assertGreaterEqual(ttot, self.duration)
AssertionError: 0.059142719999999996 not greater than or equal to 0.1
======================================================================
FAIL: test_async_wall (test_asyncio_context_vars.AsyncUsageWithContextvars)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\test_asyncio_context_vars.py", line 50, in test_async_wall
    self.assertGreaterEqual(ttot, self.duration)
AssertionError: 0.090103 not greater than or equal to 0.1
----------------------------------------------------------------------
Ran 77 tests in 17.157s
FAILED (failures=2, skipped=2)
Command exited with code 1
```

**Comment by sumerc** [comment]
This was due to a problem in clock precision in WIndows. Do NOT use Sleep(x) values smaller than 0.1. Otherwise on some cases clock is skewed and results become inconsistent.
